Repository 1024pix/eslint-config, pull requests merged in 2024-03, with the labels that each got.

#16 [TECH] Utiliser du déploiement continu
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: :rocket: Ready to Merge, cross-team

#17 [TECH] Déplacer le plugin eslint 1024pix directement dans ce projet
  index.js
  package-lock.json
  package.json
  rules/no-sinon-stub-with-args-oneliner.js
  rules/no-sinon-stub-with-args-oneliner.test.js
Labels: :rocket: Ready to Merge, cross-team

#18 Revert "[TECH] Déplacer le plugin eslint 1024pix directement dans ce projet"
  index.js
  package-lock.json
  package.json
  rules/no-sinon-stub-with-args-oneliner.js
  rules/no-sinon-stub-with-args-oneliner.test.js
Labels: cross-team

#6 [FEATURE] Trier par ordre alphabétique les imports et exports
  index.js
  package-lock.json
  package.json
Labels: :rocket: Ready to Merge, Tech Review OK

#20 [BUGFIX] Conflit entre deux clés de config
  index.js
Labels: :rocket: Ready to Merge, cross-team

#21 [TECH] Ajoute des métadonnées `npm`
  package.json
Labels: :rocket: Ready to Merge, cross-team
